version: '3'

services:
  db:
    image: postgres
    container_name: node-api-db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    # Not persisted
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    networks:
      - node-api
    expose:
      - 5432

  app:
    container_name: node-api
    tty: true
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile.prod
    networks:
      - node-api
    volumes:
      - .:/share
    ports:
      - 9090:9090
    depends_on:
      - db

networks:
  node-api:

volumes:
  postgres-data:
