version: '3'

services:
  db:
    image: postgres
    container_name: node-api-db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    # Not persisted
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    networks:
      - node-api
    expose:
      - 5432
    env_file:
      - .env
    ports:
      - ${DB_HOST_PORT}:5432

  app:
    container_name: node-api
    tty: true
    stdin_open: true
    build: .
    networks:
      - node-api
    volumes:
      - .:/share
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db

networks:
  node-api:

volumes:
  postgres-data:
